angular.module('main').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('templates/addGroundStation.html',
    "<div class=\"modal-header\"><h3 class=\"modal-title\">Add Ground Station</h3></div><div class=\"modal-body\" style=\"display: table-row\"><div style=\"float: left; display: table-cell; width: 175px; margin: 15px\"><form name=\"form\"><div class=\"control-group\" ng-class=\"{ 'has-error': form.identifier.$invalid }\"><label class=\"control-label\" for=\"identifier\">Identifier</label><input type=\"text\" name=\"identifier\" class=\"form-control\" style=\"width: 95%\" ng-model=\"gs.identifier\" ng-remote-validate=\"/configuration/groundstations/valid_id\" ng-remote-throttle=\"200\" ng-remote-method=\"GET\" ng-pattern=\"/^[a-zA-Z0-9.\\-_]{5,8}$/\" required></div><div class=\"control-group\" ng-class=\"{ 'has-error': form.callsign.$invalid }\"><label class=\"control-label\" for=\"callsign\">Callsign</label><input type=\"text\" name=\"callsign\" ng-model=\"gs.callsign\" class=\"form-control\" style=\"width: 95%\" ng-pattern=\"/^[a-zA-Z0-9]{3,8}$/\" required></div><div class=\"control-group\" ng-class=\"{ 'has-error': form.elevation.$invalid }\"><label class=\"control-label\" for=\"elevation\">Min. Antenna Elevation</label><input type=\"number\" name=\"elevation\" ng-model=\"gs.elevation\" class=\"form-control\" style=\"width: 95%\" step=\"0.01\" min=\"0\" max=\"90\" required></div><hr><label for=\"add_gs_lat\">Latitude</label><input type=\"text\" name=\"add_gs_lat\" readonly ng-model=\"markers.gsMarker.lat\" style=\"width: 95%\"><label for=\"add_gs_lng\">Longitude</label><input type=\"text\" name=\"add_gs_lng\" readonly ng-model=\"markers.gsMarker.lng\" style=\"width: 95%\"></form></div><div style=\"display: table-cell\"><leaflet id=\"addGSMap\" markers=\"markers\" center=\"center\" style=\"float: left; width: 365px; height: 365px;\n" +
    "                 margin: 15px 15px 15px 0\"></leaflet></div></div><div class=\"modal-footer\"><button class=\"btn btn-primary\" ng-click=\"ok()\" ng-disabled=\"form.$invalid\">(ok)</button> <button class=\"btn btn-warning\" ng-click=\"cancel()\">(cancel)</button></div>"
  );


  $templateCache.put('templates/addSpacecraft.html',
    "<div class=\"modal-header\"><h3 class=\"modal-title\">Add Spacecraft</h3></div><div class=\"modal-body\" style=\"display: inline-block\"><form name=\"form\"><div style=\"display: inline-block; padding: 20px\"><div style=\"float: left; width: 250px\"><div class=\"control-group\" ng-class=\"{ 'has-error': form.identifier.$invalid }\"><label class=\"control-label\" for=\"identifier\">Identifier</label><input type=\"text\" name=\"identifier\" class=\"form-control\" style=\"width: 95%\" ng-model=\"sc.identifier\" ng-remote-validate=\"/configuration/spacecraft/valid_id\" ng-remote-throttle=\"200\" ng-remote-method=\"GET\" ng-pattern=\"/^[a-zA-Z0-9.\\-_]{5,8}$/\" required></div><div class=\"control-group\" ng-class=\"{ 'has-error': form.callsign.$invalid }\"><label class=\"control-label\" for=\"callsign\">Callsign</label><input type=\"text\" name=\"callsign\" ng-model=\"sc.callsign\" class=\"form-control\" style=\"width: 95%\" ng-pattern=\"/^[a-zA-Z0-9]{3,8}$/\" required></div></div><div class=\"my-tle-menu\"><div class=\"control-group\" ng-class=\"{ 'has-error': form.tlegroup.$pristine }\"><label class=\"control-label\" for=\"tlegroup\">TLE Group (Celestrak)</label><select name=\"tlegroup\" class=\"nya-selectpicker\" ng-model=\"sc.tlegroup\" ng-init=\"initTles('Weather')\" ng-change=\"groupChanged(sc.tlegroup)\" ng-options=\"t.subsection group by t.section for t in tlegroups\"></select></div><div class=\"control-group\" ng-class=\"{ 'has-error': form.tleid.$pristine }\"><label class=\"control-label\" for=\"tleid\">TLE Identifier</label><select name=\"tleid\" class=\"nya-selectpicker\" ng-model=\"sc.tleid\" ng-options=\"t.spacecraft_tle_id for t in tles\"></select></div></div></div></form></div><div class=\"modal-footer\"><button class=\"btn btn-primary\" ng-click=\"ok()\" ng-disabled=\"form.$invalid\">(ok)</button> <button class=\"btn btn-warning\" ng-click=\"cancel()\">(cancel)</button></div>"
  );


  $templateCache.put('templates/editGroundStation.html',
    "<div class=\"modal-header\"><h3 class=\"modal-title\">Edit Ground Station</h3></div><div class=\"modal-body\" style=\"display: table-row\"><div style=\"float: left; display: table-cell; width: 175px; margin: 15px\"><form name=\"form\"><div class=\"control-group\" ng-class=\"{ 'has-error': form.identifier.$invalid }\"><label class=\"control-label\" for=\"identifier\">Identifier</label><input type=\"text\" name=\"identifier\" id=\"identifier\" class=\"form-control\" style=\"width: 95%\" ng-model=\"gs.identifier\" readonly></div><div class=\"control-group\" ng-class=\"{ 'has-error': form.callsign.$invalid }\"><label class=\"control-label\" for=\"callsign\">Callsign</label><input type=\"text\" name=\"callsign\" id=\"callsign\" ng-model=\"gs.callsign\" class=\"form-control\" style=\"width: 95%\" ng-pattern=\"/^[a-zA-Z0-9]{3,8}$/\" required></div><div class=\"control-group\" ng-class=\"{ 'has-error': form.elevation.$invalid }\"><label class=\"control-label\" for=\"elevation\">Min. Antenna Elevation</label><input type=\"number\" name=\"elevation\" id=\"elevation\" ng-model=\"gs.elevation\" class=\"form-control\" style=\"width: 95%\" step=\"0.01\" min=\"0\" max=\"90\" required></div><hr><label for=\"edit_gs_lat\">Latitude</label><input type=\"text\" name=\"edit_gs_lat\" id=\"edit_gs_lat\" readonly ng-model=\"markers.gsMarker.lat\" style=\"width: 95%\"><label for=\"edit_gs_lng\">Longitude</label><input type=\"text\" name=\"edit_gs_lng\" id=\"edit_gs_lng\" readonly ng-model=\"markers.gsMarker.lng\" style=\"width: 95%\"></form></div><div style=\"display: table-cell\"><leaflet id=\"editGSMap\" markers=\"markers\" center=\"center\" style=\"float: left; width: 365px; height:365px;\n" +
    "                 margin: 15px 15px 15px 0px\"></leaflet></div></div><div class=\"modal-footer\"><button class=\"btn btn-primary\" ng-click=\"update()\" ng-disabled=\"form.$pristine || form.$invalid\">(update)</button> <button class=\"btn btn-warning\" ng-click=\"cancel()\">(cancel)</button> <button class=\"btn btn-danger\" ng-click=\"erase()\">(remove)</button></div>"
  );


  $templateCache.put('templates/editSpacecraft.html',
    "<div class=\"modal-header\"><h3 class=\"modal-title\">Edit Spacecraft</h3></div><div class=\"modal-body\" style=\"display: inline-block\"><form name=\"form\"><div style=\"display: inline-block; padding: 20px\"><div style=\"float: left; width: 250px\"><div class=\"control-group\" ng-class=\"{ 'has-error': form.identifier.$invalid }\"><label class=\"control-label\" for=\"identifier\">Identifier</label><input type=\"text\" name=\"identifier\" class=\"form-control\" style=\"width: 95%\" ng-model=\"sc.identifier\" readonly></div><div class=\"control-group\" ng-class=\"{ 'has-error': form.callsign.$invalid }\"><label class=\"control-label\" for=\"callsign\">Callsign</label><input type=\"text\" name=\"callsign\" ng-model=\"sc.callsign\" class=\"form-control\" style=\"width: 95%\" ng-pattern=\"/^[a-zA-Z0-9]{3,8}$/\" required></div></div><div class=\"my-tle-menu\"><div class=\"control-group\" ng-class=\"{ 'has-error': form.tlegroup.$pristine }\"><label class=\"control-label\" for=\"tlegroup\">TLE Group (Celestrak)</label><select name=\"tlegroup\" class=\"nya-selectpicker\" ng-model=\"sc.tlegroup\" ng-init=\"initTles('Weather')\" ng-change=\"groupChanged(sc.tlegroup)\" ng-options=\"t.subsection group by t.section for t in tlegroups\"></select></div><div class=\"control-group\" ng-class=\"{ 'has-error': form.tleid.$pristine }\"><label class=\"control-label\" for=\"tleid\"><div style=\"display: inline-block\"><div style=\"float: left, padding: 20px\"><p>TLE Id</p></div><div><p style=\"font-size:70%\">(Current: {{ sc.savedTleId }})</p></div></div></label><select name=\"tleid\" class=\"nya-selectpicker\" ng-model=\"sc.tleid\" ng-options=\"t.spacecraft_tle_id for t in tles\"></select></div></div></div></form></div><div class=\"modal-footer\"><button class=\"btn btn-primary\" ng-click=\"update()\" ng-disabled=\"form.$invalid\">(update)</button> <button class=\"btn btn-warning\" ng-click=\"cancel()\">(cancel)</button> <button class=\"btn btn-danger\" ng-click=\"erase()\">(remove)</button></div>"
  );

}]);
