"""
   Copyright 2013, 2014 Ricardo Tubio-Pardavila

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

from django.test import TestCase
from accounts.utils import get_user_operations


class HelpersTest(TestCase):
    
    def SetUp(self):
        # self.client = Client()
        # ### Try to create initial database users for testing
        pass
    
    inp_guo = { "xxx" : "aaa", "op_43" : "verify", "opX_40" : "wrong" }
    out_guo = { "43" : "verify" }
    
    def test_get_user_operations(self):
        """
        Function test.
        
        This test checks whether the given function retrieves properly all
        user_id and operations from the given POST request, as it should be
        generated by the PendingRegView.
        
        """
        
        # response = self.client.post('/accounts/registrations/')
        result = get_user_operations(self.inp_guo)
        self.assertItemsEqual(result, self.out_guo, "Wrong result!")
        
