"""
Django tests for the <accounts> application.

"""

from django.test import TestCase
from django.test.client import Client

from accounts import helpers

class HelpersTest(TestCase):
    
    def SetUp(self):
        # self.client = Client()
        # ### Try to create initial database users for testing
        pass
    
    inp_guo = { "xxx" : "aaa", "op_43" : "verify", "opX_40" : "wrong" }
    out_guo = { "43" : "verify" }
    
    def test_get_user_operations(self):
        """
        Function test.
        
        This test checks whether the given function retrieves properly all
        user_id and operations from the given POST request, as it should be
        generated by the PendingRegView.
        
        """
        
        # response = self.client.post('/accounts/registrations/')
        result = helpers.get_user_operations(self.inp_guo)
        self.assertItemsEqual(result, self.out_guo, "Wrong result!")
        
