"""
   Copyright 2013, 2014 Ricardo Tubio-Pardavila

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""
__author__ = 'rtubiopa@calpoly.edu'

from django.test import TestCase
from services.accounts import utils as account_utils


class UtilsTest(TestCase):

    inp_guo = {"xxx": "aaa", "op_43": "verify", "opX_40": "wrong"}
    out_guo = {"43": "verify"}
    
    def test_get_user_operations(self):
        """
        Function test.
        
        This test checks whether the given function retrieves properly all
        user_id and operations from the given POST request, as it should be
        generated by the PendingRegView.
        
        """
        result = account_utils.get_user_operations(self.inp_guo)
        self.assertItemsEqual(result, self.out_guo, "Wrong result!")

    def test_random_username(self):
        """Unit test.
        Validates the generation of random user names.
        """
        name_1 = account_utils.generate_random_username()
        name_2 = account_utils.generate_random_username()

        self.assertNotEquals(
            name_1, name_2, 'Generated names should be different'
        )